### ISSUE TITLE
Support for secure-boot shim with systemd-boot?

### ISSUE THREAD

**Issue by tvogel** [openSUSE/perl-bootloader#164]
Currently, as written here https://en.opensuse.org/Systemd-boot#Secure_Boot, you need to manually move the shim into place with systemd-boot and secure boot. `sdbootutil` is focused on btrfs snapshot management and won't generalize to other file-systems, https://github.com/openSUSE/sdbootutil/issues/50#issuecomment-1970559910, and `bootctl` folks seem to still not have made up their minds if/how to integrate shim installation, https://github.com/systemd/systemd/pull/27322#issuecomment-1592525761 .

So, I am wondering, if for the time being, `perl-bootloader` could include moving the shim into place when secure boot is enabled after calling `bootctl`. Is this an option for you?

**Comment by wfeldt** [comment]
update-bootloader now relies on  sdbootutil if available. And that can handle Secure Boot.
