### ISSUE TITLE
bashism in grub2-bls feature

### ISSUE THREAD

**Issue by dirkmueller** [openSUSE/perl-bootloader#170]
Until this week, I was able to run perl-Bootloader with dash, a posix-sh like shell as /bin/sh. now not anymore. the reason is the `shellquote_raw` function (which got later moved into library with the same implementation) here:

https://github.com/openSUSE/perl-bootloader/commit/8229632e7ea768c00567fd68f5482e47555b80e9#diff-5040c10f2007cdf100863884e803f28326d282b568cd1046e2b77a0a6748d595R111-R117

variable substitutions are bash only. in order to make this compatible, it would have to use sed or the like:

```patch
-    arg=${1//\\/\\\\}
+    arg=$(echo "$1" | sed -e 's,\\/,\\\\,')
```

and the like

**Comment by wfeldt** [comment]
https://github.com/openSUSE/perl-bootloader/pull/181 should fix this.
