### ISSUE TITLE
Tools::match_section behaves incorrectly

### ISSUE THREAD

**Issue by matwey** [openSUSE/perl-bootloader#80]
Hello,

`Tools::match_section` matches every section when there are no common keys in `$sect_ref` and `$opt_ref`.

I suppose `my $match = 1;` should be `my $match = 0;`

**Comment by wfeldt** [comment]
Yes, you are right.

Note that this has been fixed in the SLE11-SP3 branch some time ago.

In general, (unfortunately) not all fixes from SLE11 (and service packs) have found their way
into master.

**Comment by wfeldt** [comment]
the old library code is not used anymore, closing
